name: 'sl_shopify_solution'
version: '1.0.0'

profile: 'sl_shopify_solution'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]

clean-targets:
  - "target"
  - "dbt_packages"


models:
  sl_shopify_solution:
    dim:
      +schema: dim
      +materialized: table
    mart:
      +schema: mart
      +materialized: table

seeds:
  sl_shopify_solution:
    +schema: dim
    +quote_columns: false
    +enabled: true
    +file_format:
      delimiter: ","
      skip_header: 1

